# Generated by Django 4.1 on 2022-09-01 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExemptionRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('date', models.DateField()),
                ('cpf', models.IntegerField()),
                ('latitude_location', models.FloatField()),
                ('longitude_location', models.FloatField()),
                ('event', models.CharField(choices=[('CHUVA EXCESSIVA', 'CHUVA EXCESSIVA'), ('GEADA', 'GEADA'), ('GRANIZO', 'GRANIZO'), ('SECA', 'SECA'), ('VENDAVAL', 'VENDAVAL'), ('RAIO', 'RAIO')], max_length=15)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
