# Generated by Django 4.1 on 2022-09-01 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemptionRequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemptionrequests',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
