# Generated by Django 4.1 on 2022-09-03 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemptionRequests', '0002_alter_exemptionrequests_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemptionrequests',
            name='crop',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exemptionrequests',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
